### ISSUE TITLE
项目tab下,当前页面listview的item条数不能填充一页，刷新会出现重复数据

### ISSUE THREAD

**Issue by ckpkover** [arvinljw/WanAndroid#1]
当前页面listview的item条数不能填充一页，刷新会出现重复数据

**Comment by ckpkover** [comment]
不是listview，是SwipeRefreshLayout

**Comment by arvinljw** [comment]
嗯，找到问题了，是项目模块下的文章列表接口，第一页是currPage是0导致的。稍后提交。
