### ISSUE TITLE
导航部分有一点问题

### ISSUE THREAD

**Issue by lidongRebirth** [arvinljw/WanAndroid#3]
点击导航部分左边的标签（个人博客-常用工具等），会出现晃动问题，闪一下才切换到点击项，知道是什么原因吗？

**Comment by arvinljw** [comment]
不知道你说的闪一下是不是执行的滑动动画，逻辑如下：
点了左边的标签之后，右边的联动，因为数据没有在同一屏内，所以其实是做了两部操作，先滑到制定的position位置，但是从上往下滑只是进入到屏幕内而已，然后需要移动到顶部，所以再执行了一次滑动，虽然不是特别连贯但是还好，也可以取消滑动动画，具体可以去代码里了解。
这种联动动画就是这样目前没有找到其他好的方式。

**Comment by lidongRebirth** [comment]
你好，没有给你说清楚，只是左边部分，例如当从常用网址点击跳到在线学习时，并不是直接切换，而是会向下滑动着选择那个在线学习，有时候相邻近的还会乱跳几次才选中所选项

**Comment by lidongRebirth** [comment]
博主，通过log日志可以看到，当点击左侧的时候，右侧的监听滑动过程的onScrolled()方法里，由于shouldScroll为false，会调用滑动左侧的方法，这就导致了点击左侧后右侧滑动时一直又在调用滑动左侧方法，所以会出现左侧会闪几次才到选中项的现象，解决办法是：每当点击时就将shouldScrolled置为true，即可解决以上现象，你看看对不对(*^▽^*)

**Comment by arvinljw** [comment]
嗯，我明白你的意思了，但是如果点击的时候就将shouldScrolled变为true，只右边滑动的时候就不会联动左边了。我大概调整了一下，点击左侧，右侧内容不再屏幕内时，shouldScrolled都为true，这时候就不会跳动；只有点击左侧，右侧内容在屏幕内时，左边的会以此滚动到相应位置。
